on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Name.txt
            url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTIDYaSPXi7AKRk-CCkIn9l6se8Qnzl0XJCSFOndKL0rBwjjT9JHBik5Zv8r9WztGjQh_O7VFEnRl-W/pub?gid=0&single=true&output=csv"
          - name: Syllable.txt
            url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTIDYaSPXi7AKRk-CCkIn9l6se8Qnzl0XJCSFOndKL0rBwjjT9JHBik5Zv8r9WztGjQh_O7VFEnRl-W/pub?gid=326391601&single=true&output=csv"
          - name: Title.txt
            url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTIDYaSPXi7AKRk-CCkIn9l6se8Qnzl0XJCSFOndKL0rBwjjT9JHBik5Zv8r9WztGjQh_O7VFEnRl-W/pub?gid=308678360&single=true&output=csv"
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update && apt-get install -y curl
          curl -L -o ./${{matrix.name}} ${{matrix.url}}
  finish:
    needs: pull
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3
        with: data
        path: |
          Name.txt
          Syllable.txt
          Title.txt
      - uses: peter-evans/create-pull-request@v3
        with:
          title: Update Data
          branch-suffix: timestamp
